foody/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^foody_1/", include("foody_1.urls", namespace="foody_1")),
    url(r"^seller/", include("seller.urls", namespace="seller")),
    url(r"^foody_1/", include("django.contrib.auth.urls")),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),


]

foody_1/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'foody_1'

urlpatterns = [
    url(r"^login/$", auth_views.LoginView.as_view(template_name="foody_1/login.html"),name='login'),
    url(r"^northindian/$", views.NorthIndianView.as_view(), name="northindian"),
    url(r"^southindian/$", views.SouthIndianView.as_view(), name="southindian"),
    url(r"^italian/$", views.ItalianView.as_view(), name="italian"),
    url(r"^chinese/$", views.ChineseView.as_view(), name="chinese"),
    url(r"^continental/$", views.ContinentalView.as_view(), name="continental"),
    url(r"^fastfood/$", views.FastFoodView.as_view(), name="fastfood"),
    url(r"^beverages/$", views.beveragesView.as_view(), name="bev"),
    url(r"^deserts/$", views.desView.as_view(), name="des"),
    url(r"^confused/$", views.ConfusedView.as_view(), name="confused"),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^result/$", views.resultpage, name="result"),


    url(r"^confused/happy/$", views.HappyView, name="happy"),
    url(r"^confused/angry/$", views.AngryView, name="angry"),
    url(r"^confused/dehydrate/$", views.DehydrateView, name="dehydrate"),
    url(r"^confused/depress/$", views.DepressiveView, name="depress"),
    url(r"^confused/excite/$", views.ExciteView, name="excite"),
    url(r"^confused/unwell/$", views.UnwellView, name="unwell"),


    url(r"^chinese/noodles/$", views.ChineseNoodlesView, name="noodles"),
    url(r"^chinese/chillyPaneer/$", views.ChineseChillyPaneerView, name="chillyPaneer"),


    url(r"^continental/ham/$", views.ContinentalHamView, name="ham"),
    url(r"^continental/springroll/$", views.ContinentalSpringRollView, name="springroll"),



    url(r"^northindian/chollebature/$", views.NorthIndianCholleView, name="cholle"),
    url(r"^northindian/rajmachawal/$", views.NorthIndianRajmaView, name="rajma"),


    url(r"^southindian/dosa/$", views.SouthIndianDosaView, name="dosa"),
    url(r"^southindian/idli/$", views.SouthIndianIdliView, name="idli"),


    url(r"^italian/garlicbread/$", views.ItalianGarlicView, name="garlic"),
    url(r"^italian/pasta/$", views.ItalianPastaView, name="pasta"),



    url(r"^fastfood/aalootikki/$", views.FastFoodAalooView, name="aalootikki"),
    url(r"^fastfood/vadapao/$", views.FastFoodPaoView, name="vadapao"),


# deserts
    url(r"^deserts/icecream/$", views.IcecreamView, name="icecream"),
    url(r"^deserts/pastries/$", views.PastriesView, name="pastries"),
    url(r"^deserts/chocolates/$", views.ChocolatesView, name="chocolates"),

# beverages
    url(r"^beverages/tea/$", views.TeaView, name="tea"),
    url(r"^beverages/softdrinks/$", views.softdrinksView, name="softdrinks"),
    url(r"^beverages/juices/$", views.juicesView, name="juices"),


    ]

foody_1/models.py
from django.db import models

# Create your models here.
class Restaurants(models.Model):
    name=models.CharField(max_length=256)
    latitude=models.DecimalField(max_digits=6,decimal_places=2)
    longitude=models.DecimalField(max_digits=6,decimal_places=2)
    rating=models.DecimalField(max_digits=6,decimal_places=2)
    cost=models.IntegerField()
    count=models.IntegerField()
    chholebature=models.IntegerField()
    rajmachawal=models.IntegerField()
    dosa=models.IntegerField()
    idli=models.IntegerField()
    noodles=models.IntegerField()
    chillypaneer=models.IntegerField()
    alootikki=models.IntegerField()
    vadapao=models.IntegerField()
    garlicbread=models.IntegerField()
    pasta=models.IntegerField()
    springroll=models.IntegerField()
    ham=models.IntegerField()
    icecream=models.IntegerField()
    pastries=models.IntegerField()
    chocolates=models.IntegerField()
    tea=models.IntegerField()
    softdrinks=models.IntegerField()
    juices=models.IntegerField()


class TrainingData(models.Model):
    rating=models.DecimalField(max_digits=6,decimal_places=2)
    distance=models.IntegerField()
    cost=models.IntegerField()
    yesno=models.IntegerField()


class MoodData(models.Model):
    Dish=models.CharField(max_length=50)
    happie=models.IntegerField()
    angrie=models.IntegerField()
    dehydratie=models.IntegerField()
    depressie=models.IntegerField()
    excitie=models.IntegerField()
    unwellie=models.IntegerField()

foody_1/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"



MOOD_CHOICES= [
    ('Happie', 'Happie'),
    ('Angrie', 'Angrie'),
    ('Dehydratie', 'Dehydratie'),
    ('Depressie', 'Depressie'),
    ('Excitie', 'Excitie'),
    ('Unwellie', 'Unwellie'),
    ]
RESTAURANT_CHOICES=[
   (1,'PizzaHut'),(2,'Dominos'),(3,'BeijingStreet'),(4,'KakeDiHatti'),(5,'ItalianJoint'),(6,'ChineseYum'),(7,'SagarRatna'),(8,'QDs'),(9,'DCafe'),(10,'Tamasha'),(11,'MasalaTrail'),
]

FOOD_CHOICES=[
   (1,'Cholle Bhature'),(2,'Rajma Chawal'),(3,'Pasta'),(4,'Garlic Bread'),(5,'Ham'),(6,'Spring Roll'),(7,'Idli'),(8,'Dosa'),(9,'Noodles'),(10,'Chilly Paneer'),(11,'Vada pao'),(12,'Aaloo Tikki'),(13,'Tea'),(14,'Ice Cream'),(15,'Chocolates'),(16,'Pastries'),(17,'Juices'),(18,'Soft Drinks')
]

class Feedback(forms.Form):

    Restaurant=forms.CharField(widget=forms.Select(choices=RESTAURANT_CHOICES))
    Food=forms.CharField(widget=forms.Select(choices=FOOD_CHOICES))
    Mood= forms.CharField(label='How are you feeling today?', widget=forms.Select(choices=MOOD_CHOICES))
    Rating=forms.DecimalField(label='Rating(On a scale of 5)', max_value=5, min_value=0)

foody_1/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy,reverse
from django.views.generic import CreateView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from .models import Restaurants,TrainingData,MoodData
import math
import numpy as np

class HomePage(TemplateView):
    template_name = "index.html"

def resultpage(request):
    form=forms.Feedback()
    if request.method=='POST':
        form=forms.Feedback(request.POST)
        if form.is_valid():
            a=form.cleaned_data['Restaurant']
            b=form.cleaned_data['Food']
            c=form.cleaned_data['Mood']
            d=form.cleaned_data['Rating']
            print(a)
            print(b)
            print(c)
            print(d)
            v=Restaurants.objects.filter(name=a).values_list()
            print(v[0])
            f=v[0][4]
            g=v[0][6]
            nv= ((f*g)+d)/(g+1)
            Restaurants.objects.filter(name=a).update(rating=nv)
            Restaurants.objects.filter(name=a).update(count=g+1)
        return render(request,'test.html',{'form':form})
    return render(request,'foody_1/result.html',{'form':form})

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "foody_1/signup.html"

class NorthIndianView(TemplateView):
    template_name = "foody_1/NorthIndian.html"

class SouthIndianView(TemplateView):
    template_name = "foody_1/SouthIndian.html"

class ItalianView(TemplateView):
    template_name = "foody_1/Italian.html"

class ChineseView(TemplateView):
    template_name = "foody_1/Chinese.html"

class ContinentalView(TemplateView):
    template_name = "foody_1/Continental.html"

class FastFoodView(TemplateView):
    template_name = "foody_1/FastFood.html"

class ConfusedView(TemplateView):
    template_name = "foody_1/Confused.html"

class desView(TemplateView):
    template_name = "foody_1/deserts.html"

class beveragesView(TemplateView):
    template_name = "foody_1/beverages.html"

def ChineseNoodlesView(request):
    restaurants=Restaurants.objects.all().values('name','latitude','longitude','rating','cost',
    'count','chholebature','rajmachawal','dosa','idli','noodles','chillypaneer','alootikki',
    'vadapao','garlicbread','pasta','springroll','ham','icecream','pastries','chocolates','tea','softdrinks','juices')
    trainingdata=TrainingData.objects.all().values('rating','cost','distance','yesno')
    temp3=list(restaurants)
    n=len(temp3)
    restaurantslist=np.zeros((n,24),np.int64)
    for i in range(n):
        restaurantslist[i][0]=temp3[i]['name']
        restaurantslist[i][1]=temp3[i]['latitude']
        restaurantslist[i][2]=temp3[i]['longitude']
        restaurantslist[i][3]=temp3[i]['rating']
        restaurantslist[i][4]=temp3[i]['cost']
        restaurantslist[i][5]=temp3[i]['count']
        restaurantslist[i][6]=temp3[i]['chholebature']
        restaurantslist[i][7]=temp3[i]['rajmachawal']
        restaurantslist[i][8]=temp3[i]['dosa']
        restaurantslist[i][9]=temp3[i]['idli']
        restaurantslist[i][10]=temp3[i]['noodles']
        restaurantslist[i][11]=temp3[i]['chillypaneer']
        restaurantslist[i][12]=temp3[i]['alootikki']
        restaurantslist[i][13]=temp3[i]['vadapao']
        restaurantslist[i][14]=temp3[i]['garlicbread']
        restaurantslist[i][15]=temp3[i]['pasta']
        restaurantslist[i][16]=temp3[i]['springroll']
        restaurantslist[i][17]=temp3[i]['ham']
        restaurantslist[i][18]=temp3[i]['icecream']
        restaurantslist[i][19]=temp3[i]['pastries']
        restaurantslist[i][20]=temp3[i]['chocolates']
        restaurantslist[i][21]=temp3[i]['tea']
        restaurantslist[i][22]=temp3[i]['softdrinks']
        restaurantslist[i][23]=temp3[i]['juices']
    temp1=np.zeros((n,1),np.int64)
    restaurantslist=np.append(restaurantslist,temp1,1)
    latitude = 10
    longitude = 10
    for i in range(n):
        restaurantslist[i][24]=math.sqrt(((restaurantslist[i][1]-latitude)*(restaurantslist[i][1]-latitude))+((restaurantslist[i][2]-longitude)*(restaurantslist[i][2]-longitude)))
    temp3=list(trainingdata)
    n=len(temp3)
    trainingdatalist=np.zeros((n,4),np.int64)
    for i in range(n):
        trainingdatalist[i][0]=temp3[i]['rating']
        trainingdatalist[i][1]=temp3[i]['cost']
        trainingdatalist[i][2]=temp3[i]['distance']
        trainingdatalist[i][3]=temp3[i]['yesno']
    # cuisine = form.cleaned_data['cuisine']
    X_train = trainingdatalist[:, [0,1,2]]
    y_train = trainingdatalist[:, 3]
    #info = pd.read_csv('BurgerInfo.csv')
    info=np.zeros((1,25),np.int64)
    n=len(restaurantslist)
    for i in range(n):
        if(restaurantslist[i][10]==1):
            info=np.vstack([info, restaurantslist[i]])
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    info=info[1:,:]
    X_test = info[:,[3,4,24]]
    y_pred = classifier.predict_proba(X_test)
    info=np.append(info,y_pred,1)
    n = len(info)
    for i in range(n-1):
        for j in range(n-1):
            if info[j][26] > info[j+1][26] :
                temp=np.zeros(27,np.int64)
                for k in range(27):
                    temp[k]=info[j][k]
                info[j]=info[j+1]
                info[j+1]=temp
    result=[]
    jelly={1:'PizzaHut',2:'Dominos',3:'BeijingStreet',4:'KakeDiHatti',5:'ItalianJoint',6:'ChineseYum',7:'SagarRatna',8:'QDs',9:'DCafe',10:'Tamasha',11:'MasalaTrail'}
    for i in range(n):
        result=np.append(result,jelly[info[i][0]])
    return render(request,'foody_1/ChineseDishes/Noodles.html',{'result':result})

def ChineseChillyPaneerView(request):
    restaurants=Restaurants.objects.all().values('name','latitude','longitude','rating','cost',
    'count','chholebature','rajmachawal','dosa','idli','noodles','chillypaneer','alootikki',
    'vadapao','garlicbread','pasta','springroll','ham','icecream','pastries','chocolates','tea','softdrinks','juices')
    trainingdata=TrainingData.objects.all().values('rating','cost','distance','yesno')
    temp3=list(restaurants)
    n=len(temp3)
    restaurantslist=np.zeros((n,24),np.int64)
    for i in range(n):
        restaurantslist[i][0]=temp3[i]['name']
        restaurantslist[i][1]=temp3[i]['latitude']
        restaurantslist[i][2]=temp3[i]['longitude']
        restaurantslist[i][3]=temp3[i]['rating']
        restaurantslist[i][4]=temp3[i]['cost']
        restaurantslist[i][5]=temp3[i]['count']
        restaurantslist[i][6]=temp3[i]['chholebature']
        restaurantslist[i][7]=temp3[i]['rajmachawal']
        restaurantslist[i][8]=temp3[i]['dosa']
        restaurantslist[i][9]=temp3[i]['idli']
        restaurantslist[i][10]=temp3[i]['noodles']
        restaurantslist[i][11]=temp3[i]['chillypaneer']
        restaurantslist[i][12]=temp3[i]['alootikki']
        restaurantslist[i][13]=temp3[i]['vadapao']
        restaurantslist[i][14]=temp3[i]['garlicbread']
        restaurantslist[i][15]=temp3[i]['pasta']
        restaurantslist[i][16]=temp3[i]['springroll']
        restaurantslist[i][17]=temp3[i]['ham']
        restaurantslist[i][18]=temp3[i]['icecream']
        restaurantslist[i][19]=temp3[i]['pastries']
        restaurantslist[i][20]=temp3[i]['chocolates']
        restaurantslist[i][21]=temp3[i]['tea']
        restaurantslist[i][22]=temp3[i]['softdrinks']
        restaurantslist[i][23]=temp3[i]['juices']
    temp1=np.zeros((n,1),np.int64)
    restaurantslist=np.append(restaurantslist,temp1,1)
    latitude = 10
    longitude = 10
    for i in range(n):
        restaurantslist[i][24]=math.sqrt(((restaurantslist[i][1]-latitude)*(restaurantslist[i][1]-latitude))+((restaurantslist[i][2]-longitude)*(restaurantslist[i][2]-longitude)))
    temp3=list(trainingdata)
    n=len(temp3)
    trainingdatalist=np.zeros((n,4),np.int64)
    for i in range(n):
        trainingdatalist[i][0]=temp3[i]['rating']
        trainingdatalist[i][1]=temp3[i]['cost']
        trainingdatalist[i][2]=temp3[i]['distance']
        trainingdatalist[i][3]=temp3[i]['yesno']
    # cuisine = form.cleaned_data['cuisine']
    X_train = trainingdatalist[:, [0,1,2]]
    y_train = trainingdatalist[:, 3]
    #info = pd.read_csv('BurgerInfo.csv')
    info=np.zeros((1,25),np.int64)
    n=len(restaurantslist)
    for i in range(n):
        if(restaurantslist[i][11]==1):
            info=np.vstack([info, restaurantslist[i]])
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    info=info[1:,:]
    X_test = info[:,[3,4,24]]
    y_pred = classifier.predict_proba(X_test)
    info=np.append(info,y_pred,1)
    n = len(info)
    for i in range(n-1):
        for j in range(n-1):
            if info[j][26] > info[j+1][26] :
                temp=np.zeros(27,np.int64)
                for k in range(27):
                    temp[k]=info[j][k]
                info[j]=info[j+1]
                info[j+1]=temp
    result=[]
    jelly={1:'PizzaHut',2:'Dominos',3:'BeijingStreet',4:'KakeDiHatti',5:'ItalianJoint',6:'ChineseYum',7:'SagarRatna',8:'QDs',9:'DCafe',10:'Tamasha',11:'MasalaTrail'}

    for i in range(n):
        result=np.append(result,jelly[info[i][0]])
    return render(request,'foody_1/ChineseDishes/ChillyPaneer.html',{'result':result})




def ContinentalHamView(request):
    restaurants=Restaurants.objects.all().values('name','latitude','longitude','rating','cost',
    'count','chholebature','rajmachawal','dosa','idli','noodles','chillypaneer','alootikki',
    'vadapao','garlicbread','pasta','springroll','ham','icecream','pastries','chocolates','tea','softdrinks','juices')

foody_1/templates/foody_1/Chinese.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>CHINESE</h1>

<ul>
  <li class='link'><a href="{% url 'foody_1:noodles' %}">

    Noodles</li>
  <li class='link'><a href="{% url 'foody_1:chillyPaneer' %}"> Chilly Paneer</li>

</ul>
<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/Confused.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>Confused</h1>

<ul>
  <li  class='link'><a href="{% url 'foody_1:happy' %}">Happie
  </li>
  <li class='link'><a href="{% url 'foody_1:angry' %}">Angrie
  </li>
  <li class='link'><a href="{% url 'foody_1:dehydrate' %}">Dehydratie
  </li>
  <li class='link'><a href="{% url 'foody_1:depress' %}">Depressie
  </li>
  <li class='link'><a href="{% url 'foody_1:excite' %}">Excitie
  </li>
  <li class='link'><a href="{% url 'foody_1:unwell' %}">Unwellie
  </li>
  <li class='link'><a href='#'>Most Searchie
  </li>
  <li class='link'><a href='#'>Most ordered at this time of the dayie
  </li>
  <li class='link'><a href='#'>Delivered instantlie
  </li>
</ul>
<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/Continental.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>CONTINENTAL</h1>


<ul>
  <li class='link'><a href="{% url 'foody_1:ham' %}"> Ham</li>
  <li class='link'><a href="{% url 'foody_1:springroll' %}"> Spring Roll</li>

</ul>
<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/FastFood.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>FAST FOOD</h1>

<ul>
  <li class='link'><a href="{% url 'foody_1:aalootikki' %}"> Aaloo Tikki</li>
  <li class='link'><a href="{% url 'foody_1:vadapao' %}"> Vada Pao</li>

</ul>

<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/Italian.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>ITALIAN</h1>



<ul>
  <li class='link'><a href="{% url 'foody_1:garlic' %}">Garlic Bread</li>
  <li class='link'><a href="{% url 'foody_1:pasta' %}">Pasta</li>

</ul>


<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/NorthIndian.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>NORTH INDIAN</h1>

<ul>
  <li class='link'><a href="{% url 'foody_1:cholle' %}">Cholle Bhature</li>
  <li class='link'><a href="{% url 'foody_1:rajma' %}"> Rajma Chawal</li>

</ul>



<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/beverages.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>BEVERAGES</h1>

<ul>
  <li class='link'><a href="{% url 'foody_1:tea' %}">Tea</li>
  <li class='link'><a href="{% url 'foody_1:softdrinks' %}">Soft Drinks</li>
  <li class='link'><a href="{% url 'foody_1:juices' %}">Juices</li>
</ul>



<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}

foody_1/templates/foody_1/deserts.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>DESSERTS</h1>



<ul>
  <li class='link'><a href="{% url 'foody_1:icecream' %}">Ice Creams</li>
  <li class='link'><a href="{% url 'foody_1:pastries' %}">Pastries</li>
  <li class='link'><a href="{% url 'foody_1:chocolates' %}">Chocolates</li>
</ul>

<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}