foody/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^foody_1/", include("foody_1.urls", namespace="foody_1")),
    url(r"^seller/", include("seller.urls", namespace="seller")),
    url(r"^foody_1/", include("django.contrib.auth.urls")),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),


]

foody_1/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'foody_1'

urlpatterns = [
    url(r"^login/$", auth_views.LoginView.as_view(template_name="foody_1/login.html"),name='login'),
    url(r"^northindian/$", views.NorthIndianView.as_view(), name="northindian"),
    url(r"^southindian/$", views.SouthIndianView.as_view(), name="southindian"),
    url(r"^italian/$", views.ItalianView.as_view(), name="italian"),
    url(r"^chinese/$", views.ChineseView.as_view(), name="chinese"),
    url(r"^continental/$", views.ContinentalView.as_view(), name="continental"),
    url(r"^fastfood/$", views.FastFoodView.as_view(), name="fastfood"),
    url(r"^beverages/$", views.beveragesView.as_view(), name="bev"),
    url(r"^deserts/$", views.desView.as_view(), name="des"),
    url(r"^confused/$", views.ConfusedView.as_view(), name="confused"),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^result/$", views.resultpage, name="result"),


    url(r"^confused/happy/$", views.HappyView, name="happy"),
    url(r"^confused/angry/$", views.AngryView, name="angry"),
    url(r"^confused/dehydrate/$", views.DehydrateView, name="dehydrate"),
    url(r"^confused/depress/$", views.DepressiveView, name="depress"),
    url(r"^confused/excite/$", views.ExciteView, name="excite"),
    url(r"^confused/unwell/$", views.UnwellView, name="unwell"),


    url(r"^chinese/noodles/$", views.ChineseNoodlesView, name="noodles"),
    url(r"^chinese/chillyPaneer/$", views.ChineseChillyPaneerView, name="chillyPaneer"),


    url(r"^continental/ham/$", views.ContinentalHamView, name="ham"),
    url(r"^continental/springroll/$", views.ContinentalSpringRollView, name="springroll"),



    url(r"^northindian/chollebature/$", views.NorthIndianCholleView, name="cholle"),
    url(r"^northindian/rajmachawal/$", views.NorthIndianRajmaView, name="rajma"),


    url(r"^southindian/dosa/$", views.SouthIndianDosaView, name="dosa"),
    url(r"^southindian/idli/$", views.SouthIndianIdliView, name="idli"),


    url(r"^italian/garlicbread/$", views.ItalianGarlicView, name="garlic"),
    url(r"^italian/pasta/$", views.ItalianPastaView, name="pasta"),



    url(r"^fastfood/aalootikki/$", views.FastFoodAalooView, name="aalootikki"),
    url(r"^fastfood/vadapao/$", views.FastFoodPaoView, name="vadapao"),


# deserts
    url(r"^deserts/icecream/$", views.IcecreamView, name="icecream"),
    url(r"^deserts/pastries/$", views.PastriesView, name="pastries"),
    url(r"^deserts/chocolates/$", views.ChocolatesView, name="chocolates"),

# beverages
    url(r"^beverages/tea/$", views.TeaView, name="tea"),
    url(r"^beverages/softdrinks/$", views.softdrinksView, name="softdrinks"),
    url(r"^beverages/juices/$", views.juicesView, name="juices"),


    ]

seller/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'seller'

urlpatterns=[
    url(r"^seller_form/$", views.seller_form.as_view(), name="seller_form"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Foody</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    {% block headblock %}
    {% endblock %}

  </head>
  <style>
  body {
  background-color: lightblue;
}
</style>
  <body>
    <nav class="navbar mynav" role="navigation" id="navbar">
    			<div class="container">
            {% if user.is_authenticated %}
            <a class="navbar-brand btn btn-default" href="{% url 'test' %}">
              <span class='glyphicon glyphicon-home'>
				Food Recommendation
               </span>
            </a>
               {% else %}
            <a class="navbar-brand btn btn-default" href="{% url 'home' %}">
              <span class='glyphicon glyphicon-home'>
				Food Recommendation
               </span>
            </a>
              {% endif %}
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                    <li><a href="{% url 'foody_1:logout' %}"><button type="button" class="btn btn-primary">LogOut</button></a></li>
    						{% else %}
                      <li><a href="{% url 'foody_1:login' %}"><button type="button" class="btn btn-primary">Login</button></a></li>
                      <li><p></p></li>
    						      <li><a href="{% url 'foody_1:signup' %}"><button type="button" class="btn btn-primary">Sign Up</button></a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        {% block fullscreen %}
        {% endblock %}
        <div class="container mycontent">
          {% block content %}

          {% endblock %}
        </div>

  <canvas id="canvas"></canvas>

  </body>
  <!-- <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
</html>

templates/index.html
{% extends "base.html" %}
{% block headblock %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}

<div class="container-fluid">
<div class="jumbotron">
  <h1>It recommends food based on your mood</h1>
  <p>The first food recommending and delivery app that gives your mood the prime importance</p>
</div>
</div>

<br>
<br>
{% if not user.is_authenticated %}

<h2 align="center" ><a href="{% url 'seller:seller_form' %}" class='sell' ><p class="btn btn-primary btn-lg">Wanna sell on Moodie Foodie?</p></a></h2>
{% endif %}
<style>
body {
  background-image: url("https://thumbs.dreamstime.com/b/asian-food-background-various-ingredients-rustic-stone-top-view-vietnam-thai-cuisine-148762904.jpg");
}
</style>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
  <!-- <link rel="stylesheet" href="{% static 'simplesocial/css/instr.css' %}"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'simplesocial/css/image.css' %}">
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<div class="container-fluid">
      <h2 align='center' class='confused'>Cuisines</h2>
      <div class="row">
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:northindian' %}"><img src="https://blog.travelkhana.com/food/wp-content/uploads/sites/5/2017/04/north-india.jpg" alt="">North Indian</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:southindian' %}"><img  src="http://www.foodofy.com/wp-content/uploads/2015/07/11014_14_site_clear.jpeg" alt="">South Indian</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:italian' %}"><img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPwz6Gd0asAyRwxyzSbSVrSxSmdL1Wmjiodii2xWaIc45rORnM" alt="">Italian</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:chinese' %}"><img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcSYMas-ewbaO2FOCTUIVNS2M_65fasV70Tbd8m9fDPRcfFO9QBQ" alt="">Chinese</div>

          <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:confused' %}"><img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjaJTI9jykkJxkq5p-NCu3o_h2gXHwrrQlp6yCXSMbv5YYRZUx" alt="">  Feelin MOODIE? Can't decide? We can help! :D</div>


        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:continental' %}"><img  src="http://www.differencebetween.info/sites/default/files/images/3/continental.jpg" alt="">Continental</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:fastfood' %}"><img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTJZxq4GADhQdCWd-kPvWwvTVdCD8JcC8S8KxFY4NfHSQznGW_" alt="">Fast Food</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:bev' %}"><img  src="https://www.tutorialspoint.com/food_and_beverage_services/images/non_alcoholic_beverages.jpg" alt="">Beverages</div>
        <div class="col-lg-4 col-xs-6 thumbnail hello"><a href="{% url 'foody_1:des' %}"><img  src="https://i.ytimg.com/vi/vvR1pde64ZA/maxresdefault.jpg" alt="">Desserts</div>



      </div>

    </div>

<style media="screen">


  .hello{
    font-size: 20px;
    text-align: center;
      display:block;
      height: 320px;
      width: 370px;
      margin: auto;
  }
 .container{
   margin-left: 130px;

 }
  .confused{
    font-size: 50px;
    text-align: center;
    font-family: 'Poor Story', cursive;
  }
</style>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% load staticfiles %}
{% block headblock %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
{% endblock %}

{% block fullscreen %}
<h1 class='head_mansi'>THANKS</h1>


<style media="screen">
.link{
  text-align: center;
    display: block;
  font-size: 30px;
font-family: 'Poor Story', cursive;
}
.under_tag{
  color:black;
  font-size: 25px;
  font-family: 'Poor Story', cursive;
}
.head_mansi{

  color:black;
  font-size: 100px;
  text-align: center;
  font-family: 'Poor Story', cursive;
}
</style>
{% endblock %}